name: Compile VeloStrap via PyInstaller

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      
      - run: pip install pyinstaller
      
      - run: pyinstaller --onefile --clean --distpath . VeloStrap.py
      
      - name: Send Release Discord
        run: |
          curl -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" `
            -H "Content-Type: application/json" `
            -d "{\"content\": \"🚀 **New VeloStrap Release (Stable or not) Ready!**\nVersion: ${{ github.ref_name }}\n# 📁 Download\nDownload the latest version from either the official Github(<https://github.com/NewPythonX-NPX/VeloStrap/releases> or itch.io(<https://newpythonx.itch.io/velostrap-npx> (P.S itch.io won't get snapshot releases)\"}"
        shell: powershell
      
      - name: Create ZIP
        run: |
          powershell Compress-Archive -Path VeloStrap.exe -DestinationPath VeloStrap_${{ github.ref_name }}.zip
          
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: VeloStrap_${{ github.ref_name }}.zip

      - name: Download Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default
          Expand-Archive butler.zip -DestinationPath .
        
      - name: Push to Itch.io
        run: |
          ./butler push VeloStrap_${{ github.ref_name }}.zip newpythonx/velostrap-npx:windows --userversion ${{ github.ref_name }}
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
